
language: python

python:  
  - "3.6.4"

 
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  
  
 
  
script:   
  - pytest test.py
  - coverage report
 
after_success:
  - coveralls
