language: python

python:  
  - "3.6"
 
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
 
  
script:   
  - pytest --cov=app test
  - coverage report
 
after_success:
  - coveralls