
language: python

python:  
  - "3.6.4"

 
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  
  
 
  
script:   
  - py.test test.py --with-coverage  --cover-package=app

after_success:
  - coveralls
