
language: python

python:  
  - "3.6.4"

 
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  
  
 
  
script:   
  - py.test  --cov-report term --cov=app test.py
  - coverage report

after_success:
  - coveralls
