
language: python

python:  
  - "3.7.1"

 
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "python -m pip install -U pip"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"
 
  
script:   
  - pytest test.py
  - coverage report
 
after_success:
  - coveralls
