
language: python

python:  
  - "3.6.4"

 
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install pytest "
  
 
  
script:   
  - py.test  --cov=app 
  - coverage report
 
after_success:
  - coveralls
