
language: python

python:  
  - "3.6.4"

 
install:
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-cov"
  - "pip install coveralls"
  
  
 
  
script:   
  - py.test test.py 

after_success:
  - coveralls
