/**
 * Sample Application Flow OAuth2 Project
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * This is an example opeartion to show how security is applied to the call.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def exampleGet(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/NicholusMuwonge/IReporter/1.0.0", "/example", "application/json")
      .withSuccessResponse[Unit](200)
        /**
   * This operation shows how to override the global security defined above, as we want to open it up for all users.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   */
  def pingGet(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/NicholusMuwonge/IReporter/1.0.0", "/ping", "application/json")
      .withSuccessResponse[Unit](200)
      

}

